---

- name: Sudo without password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { line: "#Password less sudo", regexp: '^#Password' }
    - { line: "{{ user.name }} ALL=(ALL) NOPASSWD: ALL", regexp: '^{{ user.name }}' }

