---
- name: Perform upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: Enable universe and multiverse repos
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb http://lv.archive.ubuntu.com/ubuntu/ {{ ubuntu_codename }} universe"
    - "deb http://lv.archive.ubuntu.com/ubuntu/ {{ ubuntu_codename }} multiverse"

- name: Install essential libs
  apt:
    name:
      - build-essential
      - python
      - python-pip
      - snapd

- name: Install various tools
  apt:
    name:
      - htop
      - ncdu
      - curl
      - wget